/**
 * Live + cached + bundled-snapshot catalog of providers from models.dev.
 *
 * Load order (mirrors OpenCode's pattern):
 *   1. in-memory cache (per service-worker session)
 *   2. chrome.storage.local cache (if mtime within freshness TTL)
 *   3. bundled snapshot (./snapshot.json)
 *   4. live fetch from https://models.dev/api.json
 *   5. empty {}
 *
 * `refreshCatalog({force})` updates storage and the in-memory cache;
 * a 5-minute freshness gate prevents redundant network requests.
 *
 * The background script schedules a 60-minute refresh via chrome.alarms
 * (see entrypoints/background). React UI consumers subscribe to
 * chrome.storage.onChanged via the `useProviders` hook.
 */

import { STORAGE_KEYS } from "@/lib/constants";
import bundledSnapshot from "./snapshot.json";
import { ModelsDevCatalogSchema, type ModelsDevCatalog } from "./types";

const SOURCE_URL = "https://models.dev/api.json";
const FRESHNESS_MS = 5 * 60 * 1000; // skip refetch if cache mtime within this
const FETCH_TIMEOUT_MS = 10_000;

interface CachedCatalog {
  catalog: ModelsDevCatalog;
  fetchedAt: number; // epoch ms
}

interface InMemoryState {
  cached: CachedCatalog | null;
  inflight: Promise<ModelsDevCatalog> | null;
}

const memory: InMemoryState = { cached: null, inflight: null };

function isChromeStorageAvailable(): boolean {
  return (
    typeof chrome !== "undefined" &&
    typeof chrome.storage !== "undefined" &&
    typeof chrome.storage.local !== "undefined"
  );
}

async function loadFromStorage(): Promise<CachedCatalog | null> {
  if (!isChromeStorageAvailable()) return null;
  try {
    const result = await chrome.storage.local.get(STORAGE_KEYS.MODELS_DEV_CATALOG);
    const raw = result[STORAGE_KEYS.MODELS_DEV_CATALOG];
    if (!raw || typeof raw !== "object") return null;
    const { catalog, fetchedAt } = raw as Partial<CachedCatalog>;
    if (typeof fetchedAt !== "number" || !catalog) return null;
    // Tolerate older payloads that didn't pass the schema; reject silently.
    const parsed = ModelsDevCatalogSchema.safeParse(catalog);
    if (!parsed.success) return null;
    return { catalog: parsed.data, fetchedAt };
  } catch {
    return null;
  }
}

async function writeToStorage(value: CachedCatalog): Promise<void> {
  if (!isChromeStorageAvailable()) return;
  try {
    await chrome.storage.local.set({ [STORAGE_KEYS.MODELS_DEV_CATALOG]: value });
  } catch {
    // Quota errors etc. are non-fatal — we still have memory + snapshot.
  }
}

function loadSnapshot(): ModelsDevCatalog {
  // The snapshot is generated by `pnpm refresh:models` and Zod-validated
  // at build time; trust it here without re-validating to keep startup fast.
  return bundledSnapshot as unknown as ModelsDevCatalog;
}

async function fetchLive(): Promise<ModelsDevCatalog> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(SOURCE_URL, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = (await res.json()) as unknown;
    return ModelsDevCatalogSchema.parse(json);
  } finally {
    clearTimeout(timer);
  }
}

async function fetchLiveWithRetry(): Promise<ModelsDevCatalog> {
  try {
    return await fetchLive();
  } catch (firstErr) {
    // One retry on transient failure (network blips, brief 5xx).
    try {
      return await fetchLive();
    } catch (secondErr) {
      console.warn("[models-dev] live fetch failed twice", firstErr, secondErr);
      throw secondErr;
    }
  }
}

/**
 * Returns the current catalog. Resolves from the fastest available
 * source; never throws — falls back to the bundled snapshot or empty.
 */
export async function getCatalog(): Promise<ModelsDevCatalog> {
  if (memory.cached) return memory.cached.catalog;
  if (memory.inflight) return memory.inflight;

  memory.inflight = (async () => {
    const fromStorage = await loadFromStorage();
    if (fromStorage) {
      memory.cached = fromStorage;
      return fromStorage.catalog;
    }
    // No storage cache — use the snapshot immediately so the UI has data.
    const snapshot = loadSnapshot();
    memory.cached = { catalog: snapshot, fetchedAt: 0 };
    return snapshot;
  })();

  try {
    return await memory.inflight;
  } finally {
    memory.inflight = null;
  }
}

/** Returns when the cache was last refreshed (epoch ms), or null if never. */
export async function getLastUpdated(): Promise<number | null> {
  if (memory.cached) return memory.cached.fetchedAt || null;
  const fromStorage = await loadFromStorage();
  return fromStorage?.fetchedAt ?? null;
}

export interface RefreshOptions {
  /** Force a network fetch even if the cache is fresh. */
  force?: boolean;
}

export interface RefreshResult {
  fetchedAt: number;
  providerCount: number;
  modelCount: number;
}

/**
 * Refreshes the catalog from the network, persists it, and updates the
 * in-memory cache. No-ops if the cache is within the freshness window
 * unless `{force: true}` is passed.
 *
 * Returns null if the refresh was skipped (still fresh) or failed silently.
 */
export async function refreshCatalog(
  options: RefreshOptions = {},
): Promise<RefreshResult | null> {
  const { force = false } = options;
  const now = Date.now();

  if (!force) {
    const fromStorage = memory.cached ?? (await loadFromStorage());
    if (fromStorage && now - fromStorage.fetchedAt < FRESHNESS_MS) {
      memory.cached = fromStorage;
      return null;
    }
  }

  try {
    const catalog = await fetchLiveWithRetry();
    const value: CachedCatalog = { catalog, fetchedAt: Date.now() };
    memory.cached = value;
    await writeToStorage(value);
    return {
      fetchedAt: value.fetchedAt,
      providerCount: Object.keys(catalog).length,
      modelCount: Object.values(catalog).reduce(
        (acc, p) => acc + Object.keys(p.models).length,
        0,
      ),
    };
  } catch (err) {
    console.warn("[models-dev] refresh failed", err);
    return null;
  }
}

/** Clears the in-memory cache; useful for tests or after a manual refresh. */
export function _resetCacheForTests(): void {
  memory.cached = null;
  memory.inflight = null;
}

/**
 * Drops the in-memory cache so the next `getCatalog()` call re-reads
 * from `chrome.storage.local`. Call this when the storage key is known
 * to have changed in another context (e.g. a background refresh wrote
 * a new live catalog while the page-context cache was holding the
 * bundled snapshot).
 *
 * Without this, `getCatalog()` short-circuits on `memory.cached` for
 * the lifetime of the page and consumers like `useProviders` never
 * see catalog updates that landed after the first `getCatalog()` call.
 */
export function invalidateCache(): void {
  memory.cached = null;
  memory.inflight = null;
}
