/**
 * `BrowserDriver` implementation backed by Playwright. Used by the bench
 * harness to run the OpenBrowse agent headlessly outside the Chrome
 * extension runtime.
 *
 * Design notes:
 *
 *  - Playwright's `BrowserContext` exposes `newCDPSession(page)`, which
 *    speaks the same Chrome DevTools Protocol that the production extension
 *    uses via `chrome.debugger`. That means `snapshot-capture.ts` and every
 *    page-interacting tool can share the same code path — Playwright simply
 *    pipes CDP commands through a different transport.
 *
 *  - Tabs are tracked by stable string ids (e.g. `t0`, `t1`) generated by
 *    this driver. Real Playwright `Page` objects don't have a portable id
 *    of their own, so we keep a side map `tabId → Page`.
 *
 *  - Per the v1 design (see spec): single tab per trial. The driver tracks
 *    multiple pages (because users can open new tabs via JS or links) but
 *    the agent's "active tab" pointer is what tools key off, and bench tasks
 *    are curated to be one-tab.
 *
 *  - `sendToContentScript` is the legacy CSS-selector fallback path used by
 *    a few extension tools (`scrollPage`, `readPage`, the
 *    `clickBySelector` branch of `clickElement`, etc.). The extension
 *    delivers these via `chrome.tabs.sendMessage` to a real content script.
 *    Playwright has no content script — instead we translate each message
 *    type into the equivalent `page.evaluate(...)`. Adding a new message
 *    type means adding a translation here.
 */

import {
  chromium,
  type Browser,
  type BrowserContext,
  type CDPSession,
  type Page,
} from "playwright";
import type { BrowserDriver, BrowserTabInfo, TabId } from "@agent/driver";

interface TrackedPage {
  id: TabId;
  page: Page;
  cdp: CDPSession;
}

export interface PlaywrightDriverOptions {
  headless?: boolean;
  /** Slowdown for debugging (ms between Playwright actions). */
  slowMo?: number;
  /** Defaults to 1280x800, a sensible viewport for most web tasks. */
  viewport?: { width: number; height: number };
  /** User-agent override. Default: Playwright's chromium UA. */
  userAgent?: string;
  /**
   * Optional directory for Playwright to record video into. When set, the
   * browser context is created with `recordVideo` and the driver tracks the
   * video file path so the runner can rename it to a stable per-trial
   * filename via `saveAndCloseVideo()`. Set to undefined / omit to disable.
   */
  recordVideoDir?: string;
}

export class PlaywrightDriver implements BrowserDriver {
  protected browser: Browser;
  protected context: BrowserContext;
  protected pages = new Map<TabId, TrackedPage>();
  protected activeTabId: TabId | null = null;
  protected nextId = 0;
  protected recordVideoDir: string | undefined;

  /** Construct a fresh driver — opens a new isolated browser context. */
  static async launch(opts: PlaywrightDriverOptions = {}): Promise<PlaywrightDriver> {
    // Headed by default, per the spec's resolved decisions: the screenshot
    // tool relies on real rendered pixels which headless Chrome doesn't
    // produce reliably on many sites.
    const browser = await chromium.launch({
      headless: opts.headless ?? false,
      slowMo: opts.slowMo,
    });
    const viewport = opts.viewport ?? { width: 1280, height: 800 };
    const context = await browser.newContext({
      viewport,
      userAgent: opts.userAgent,
      // recordVideo MUST be set at context creation. Playwright captures the
      // entire context lifetime; you can't enable it mid-session.
      ...(opts.recordVideoDir
        ? { recordVideo: { dir: opts.recordVideoDir, size: viewport } }
        : {}),
    });
    return new PlaywrightDriver(browser, context, opts.recordVideoDir);
  }

  protected crashed = false;

  protected constructor(
    browser: Browser,
    context: BrowserContext,
    recordVideoDir: string | undefined,
  ) {
    this.browser = browser;
    this.context = context;
    this.recordVideoDir = recordVideoDir;
    // Auto-track pages opened via window.open / target=_blank so listTabs
    // sees them. New pages start un-attached; we lazily create a CDP session
    // on first sendCommand to avoid wasting CDP attaches on incidental tabs.
    context.on("page", (page) => {
      void this.attachPage(page);
    });
  }

  protected checkCrashed() {
    if (this.crashed) {
      throw new Error("Browser tab crashed or was closed unexpectedly");
    }
  }

  /**
   * Save the recorded video to a stable path then tear down the browser.
   * Must be called instead of `close()` when video recording is enabled —
   * Playwright finalizes the video only when the context closes, so the
   * order matters: get a video handle, close the context, then `saveAs`
   * the finalized file.
   *
   * Returns the absolute path of the saved video, or null if recording was
   * disabled or no pages had been opened. Cleans up any auto-named
   * `page@<hash>.webm` orphan files Playwright creates for secondary pages.
   */
  async closeAndSaveVideo(targetPath: string): Promise<string | null> {
    if (!this.recordVideoDir) {
      await this.close();
      return null;
    }
    // Grab a handle to the video before closing — only the first page's
    // video is reliably captured for our single-tab-per-trial model. If
    // multiple pages were opened, the others will be discarded.
    const allTrackedPages = [...this.pages.values()];
    const firstPage = allTrackedPages[0]?.page;
    const video = firstPage?.video();
    // Detach all CDP sessions before closing context — otherwise Playwright
    // sometimes hangs waiting for them on close.
    for (const tracked of this.pages.values()) {
      await tracked.cdp.detach().catch(() => {});
    }
    await this.context.close().catch(() => {});
    if (video) {
      await video.saveAs(targetPath).catch(() => {});
      // Best-effort cleanup of the auto-named original AND any orphan
      // page@*.webm files from secondary pages. Without this the videos
      // dir accumulates noise — the agent often opens incidental tabs
      // (favicon, OG-preview) that each get their own auto-named file.
      await video.delete().catch(() => {});
      await this.deleteOrphanVideos(targetPath);
    }
    await this.browser.close().catch(() => {});
    return video ? targetPath : null;
  }

  /**
   * Remove any `*.webm` files in `recordVideoDir` whose path doesn't match
   * the trial-saved targetPath. Best-effort and limited to files modified
   * since this driver was constructed (so we don't trample other concurrent
   * trials' artifacts in the same directory).
   */
  protected async deleteOrphanVideos(savedPath: string): Promise<void> {
    if (!this.recordVideoDir) return;
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    try {
      const entries = await fs.readdir(this.recordVideoDir);
      for (const name of entries) {
        if (!name.endsWith(".webm")) continue;
        const full = path.resolve(this.recordVideoDir, name);
        if (full === savedPath) continue;
        // Only delete the auto-named pattern Playwright uses
        // (page@<hex32>.webm). Anything else is probably a previously-
        // saved trial's video — leave it alone.
        if (!/^page@[0-9a-f]{32}\.webm$/.test(name)) continue;
        await fs.unlink(full).catch(() => {});
      }
    } catch {
      // best-effort
    }
  }

  /** Cleanly tear down the browser. Caller is responsible for invoking this. */
  async close(): Promise<void> {
    await this.context.close().catch(() => {});
    await this.browser.close().catch(() => {});
  }

  // -------------------------------------------------------------------------
  // BrowserDriver implementation
  // -------------------------------------------------------------------------

  async sendCommand<T = unknown>(
    tabId: TabId,
    method: string,
    params?: Record<string, unknown>,
  ): Promise<T> {
    this.checkCrashed();
    const tracked = await this.requirePage(tabId);
    // Playwright's CDPSession.send returns the raw protocol result, which is
    // the same shape the extension's `chrome.debugger.sendCommand` returns.
    // Cast through unknown because the SDK's `send` overload uses a generic
    // ProtocolMethod literal we don't match here — the typecheck would
    // require us to copy or re-derive the union of all CDP methods.
    return (await tracked.cdp.send(method as never, params as never)) as T;
  }

  async getActiveTab(): Promise<BrowserTabInfo> {
    this.checkCrashed();
    if (this.activeTabId == null) {
      // Bench tasks always begin with `navigate(startUrl)`, which creates
      // and pins a tab. If we got here without one, the runner skipped
      // its setup step.
      throw new Error(
        "PlaywrightDriver: no active tab. Call navigate(startUrl) before reading tab state.",
      );
    }
    const tracked = this.pages.get(this.activeTabId);
    if (!tracked) {
      throw new Error(
        `PlaywrightDriver: active tab id ${String(this.activeTabId)} no longer exists.`,
      );
    }
    return await this.toTabInfo(tracked);
  }

  async setActiveTab(tabId: TabId | null): Promise<void> {
    this.checkCrashed();
    if (tabId != null && !this.pages.has(tabId)) {
      throw new Error(`PlaywrightDriver: unknown tab id ${String(tabId)}`);
    }
    this.activeTabId = tabId;
  }

  getActiveTabId(): TabId | null {
    return this.activeTabId;
  }

  async listTabs(): Promise<BrowserTabInfo[]> {
    this.checkCrashed();
    const out: BrowserTabInfo[] = [];
    for (const tracked of this.pages.values()) {
      out.push(await this.toTabInfo(tracked));
    }
    return out;
  }

  async updateTabUrl(tabId: TabId, url: string): Promise<void> {
    this.checkCrashed();
    const tracked = await this.requirePage(tabId);
    await tracked.page.goto(url);
  }

  async createTab(
    url: string,
    _opts: { active?: boolean } = {},
  ): Promise<TabId> {
    this.checkCrashed();
    const page = await this.context.newPage();
    const tracked = await this.attachPage(page);
    await page.goto(url);
    return tracked.id;
  }

  async waitForLoad(tabId: TabId, timeoutMs = 15_000): Promise<void> {
    this.checkCrashed();
    const tracked = await this.requirePage(tabId);
    // Mirror the extension's "complete" semantics — wait until the page is
    // fully loaded, not just DOM-ready. Some bench tasks involve client-side
    // routing where this is too aggressive; use `domcontentloaded` if those
    // start dominating.
    await tracked.page.waitForLoadState("load", { timeout: timeoutMs });
  }

  async closeTab(tabId: TabId): Promise<void> {
    const tracked = this.pages.get(tabId);
    if (!tracked) return;
    await tracked.cdp.detach().catch(() => {});
    await tracked.page.close().catch(() => {});
    this.pages.delete(tabId);
    if (this.activeTabId === tabId) this.activeTabId = null;
  }

  /**
   * Translate the legacy content-script messages into Playwright equivalents.
   * Each `type` corresponds to a message the extension's content script
   * handles natively.
   */
  async sendToContentScript<T = unknown>(
    tabId: TabId,
    message: Record<string, unknown>,
  ): Promise<T> {
    this.checkCrashed();
    const tracked = await this.requirePage(tabId);
    const type = message["type"] as string;
    switch (type) {
      case "CHAT_SCROLL_PAGE": {
        const direction = (message["direction"] as "up" | "down") ?? "down";
        const amount = (message["amount"] as number) ?? 600;
        const dy = direction === "down" ? amount : -amount;
        await tracked.page.evaluate(
          ([offset]) => window.scrollBy({ top: offset, behavior: "instant" as ScrollBehavior }),
          [dy] as const,
        );
        return { success: true } as T;
      }
      case "CHAT_EXTRACT_CONTENT": {
        const result = await tracked.page.evaluate(() => {
          const title = document.title ?? "";
          const h1 = document.querySelector("h1")?.textContent?.trim() ?? "";
          const description =
            document
              .querySelector('meta[name="description"]')
              ?.getAttribute("content") ?? "";
          const bodyText =
            (document.body?.innerText ?? "").slice(0, 10_000);
          const links = Array.from(document.querySelectorAll("a[href]"))
            .slice(0, 50)
            .map((a) => ({
              text: (a.textContent ?? "").trim(),
              href: (a as HTMLAnchorElement).href,
            }));
          return {
            url: location.href,
            title,
            h1,
            description,
            bodyText,
            links,
          };
        });
        return result as T;
      }
      case "CHAT_CLICK_ELEMENT": {
        const selector = message["selector"] as string;
        try {
          await tracked.page.click(selector, { timeout: 3_000 });
          return { success: true } as T;
        } catch (err) {
          return {
            success: false,
            error: err instanceof Error ? err.message : String(err),
          } as T;
        }
      }
      case "CHAT_TYPE_IN_ELEMENT": {
        const selector = message["selector"] as string;
        const text = message["text"] as string;
        const clearFirst = (message["clearFirst"] as boolean) ?? true;
        try {
          if (clearFirst) {
            await tracked.page.fill(selector, text, { timeout: 3_000 });
          } else {
            await tracked.page.locator(selector).pressSequentially(text, {
              timeout: 3_000,
            });
          }
          return { success: true } as T;
        } catch (err) {
          return {
            success: false,
            error: err instanceof Error ? err.message : String(err),
          } as T;
        }
      }
      default:
        return {
          success: false,
          error: `PlaywrightDriver: no handler for content-script message type "${type}"`,
        } as T;
    }
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------

  protected async attachPage(page: Page): Promise<TrackedPage> {
    // Idempotent: if we've already wrapped this page, return it.
    for (const existing of this.pages.values()) {
      if (existing.page === page) return existing;
    }
    const id = `t${this.nextId++}`;
    const cdp = await this.context.newCDPSession(page);
    const tracked: TrackedPage = { id, page, cdp };
    this.pages.set(id, tracked);
    page.on("close", () => {
      this.pages.delete(id);
      if (this.activeTabId === id) this.activeTabId = null;
    });
    return tracked;
  }

  protected async requirePage(tabId: TabId): Promise<TrackedPage> {
    const tracked = this.pages.get(tabId);
    if (!tracked) {
      throw new Error(
        `PlaywrightDriver: unknown tab id ${String(tabId)}. Known: [${Array.from(this.pages.keys()).join(", ")}]`,
      );
    }
    return tracked;
  }

  protected async toTabInfo(tracked: TrackedPage): Promise<BrowserTabInfo> {
    let title = "";
    try {
      title = await tracked.page.title();
    } catch {
      // page may have been closed mid-call
    }
    return {
      id: tracked.id,
      url: tracked.page.url(),
      title,
      active: tracked.id === this.activeTabId,
    };
  }
}
