name: Feature request
description: Suggest a new feature or improvement.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: A clear, concise description of the problem. Ex. "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: dropdown
    id: contribute
    attributes:
      label: Are you willing to contribute?
      options:
        - "Yes, I can submit a PR"
        - "Yes, but I need guidance"
        - "No, I cannot contribute at this time"
    validations:
      required: true
