import { createOpenAI } from "@ai-sdk/openai";
import type { ProviderDefinition } from "./types";

export const definition: ProviderDefinition = {
  id: "openai",
  name: "OpenAI",
  icon: { light: "openai.svg", dark: "openai-dark.svg" },
  description: "GPT-5.5, o-series reasoning, and GPT-4.1 models",
  setup: "byok",
  configSchema: [
    { key: "apiKey", label: "API Key", type: "password", required: true, placeholder: "sk-..." },
  ],
  models: [
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      description: "Most capable OpenAI model with advanced reasoning",
      capabilities: ["chat", "tools", "vision", "thinking"],
      intelligence: "high",
      speed: "slow",
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      pricing: { inputPer1M: 5, outputPer1M: 30 },
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      description: "Strong flagship with broad capabilities",
      capabilities: ["chat", "tools", "vision", "thinking"],
      intelligence: "high",
      speed: "medium",
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      pricing: { inputPer1M: 2.50, outputPer1M: 15 },
    },
    {
      id: "gpt-5-mini",
      name: "GPT-5 Mini",
      description: "Compact GPT-5 variant balancing speed and capability",
      capabilities: ["chat", "tools", "vision", "thinking"],
      intelligence: "medium",
      speed: "fast",
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      pricing: { inputPer1M: 0.25, outputPer1M: 2 },
    },
    {
      id: "gpt-5-nano",
      name: "GPT-5 Nano",
      description: "Lightweight and fast for simple tasks",
      capabilities: ["chat", "tools", "vision", "thinking"],
      intelligence: "low",
      speed: "fast",
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      pricing: { inputPer1M: 0.05, outputPer1M: 0.40 },
    },
    {
      id: "gpt-4.1",
      name: "GPT-4.1",
      description: "Large context model with strong instruction following",
      capabilities: ["chat", "tools", "vision"],
      intelligence: "medium",
      speed: "medium",
      contextWindow: 1_047_576,
      maxOutputTokens: 32_768,
      pricing: { inputPer1M: 2, outputPer1M: 8 },
    },
    {
      id: "gpt-4.1-mini",
      name: "GPT-4.1 Mini",
      description: "Affordable large-context model for everyday tasks",
      capabilities: ["chat", "tools", "vision"],
      intelligence: "medium",
      speed: "fast",
      contextWindow: 1_047_576,
      maxOutputTokens: 32_768,
      pricing: { inputPer1M: 0.40, outputPer1M: 1.60 },
    },
    {
      id: "gpt-4.1-nano",
      name: "GPT-4.1 Nano",
      description: "Ultra-fast and cheapest for classification and extraction",
      capabilities: ["chat", "tools", "vision"],
      intelligence: "low",
      speed: "fast",
      contextWindow: 1_047_576,
      maxOutputTokens: 32_768,
      pricing: { inputPer1M: 0.10, outputPer1M: 0.40 },
    },
  ],
  createLanguageModel(config, modelId) {
    const openai = createOpenAI({ apiKey: config.apiKey });
    return openai(modelId);
  },
};
